SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `PROJECTS` (
`ID` int(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `VISIBILITY` enum('PUBLIC','PRIVATE') NOT NULL,
  `RMQ` varchar(255) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `SUBSCRIBE` (
`ID` int(255) NOT NULL,
  `USER` int(255) NOT NULL,
  `PROJECT` int(255) NOT NULL,
  `STATUS` enum('MANAGER','CONTRIBUTOR') NOT NULL,
  `RMQ` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `USERS` (
`ID` int(255) NOT NULL,
  `NICKNAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `RMQ` varchar(255) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=12 ;


ALTER TABLE `PROJECTS`
 ADD PRIMARY KEY (`ID`);

ALTER TABLE `SUBSCRIBE`
 ADD PRIMARY KEY (`ID`), ADD KEY `USER` (`USER`,`PROJECT`), ADD KEY `PROJECT` (`PROJECT`);

ALTER TABLE `USERS`
 ADD PRIMARY KEY (`ID`);


ALTER TABLE `PROJECTS`
MODIFY `ID` int(255) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
ALTER TABLE `SUBSCRIBE`
MODIFY `ID` int(255) NOT NULL AUTO_INCREMENT;
ALTER TABLE `USERS`
MODIFY `ID` int(255) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=12;

ALTER TABLE `SUBSCRIBE`
ADD CONSTRAINT `SUBSCRIBE_ibfk_1` FOREIGN KEY (`USER`) REFERENCES `USERS` (`ID`),
ADD CONSTRAINT `SUBSCRIBE_ibfk_2` FOREIGN KEY (`PROJECT`) REFERENCES `PROJECTS` (`ID`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
