#!/bin/bash
#Script d'ajout d'un utilisateur Unix sur le serveur Meetspace

#Ajout de l'utilisateur Unix:

name=toto
password=pass
mkpassword=`mkpasswd $password`
echo "name = $name "
echo "password = $password "
echo "mkpasswd = $mkpassword "
useradd --home /home/$name --gid meetspace_user --password $mkpassword $name --shell "/bin/MySecureShell"



#cat /etc/passwd | grep -v $name
#sed -i -e "s/chaines1/chaine2/g" fichier 
#echo 'Version: TAG_01' | sed 's/^Version: TAG_[0-9][0-9]/Version: TAG_02/'
#toto:x:1008:1007::/home/toto:/bin/sh


#echo 'vmail:x:1006:1006::/home/vmail:/bin/sh' | sed 's/^toto: /bin/sh//bin/bash/'



#Mise en place de MySecureShell

#Identifiez l'utilisateur dont vous voulez restreindre l'accès à son dossier. Son pseudo débute la ligne à modifier. Une fois que vous avez trouvé, remplacez /bin/bash par /bin/MySecureShell.
#Lui dire : A la ligne commençant par $nom remplacer /bin/bash par /bin/MySecureShell
